### PR TITLE
Improve Altitude formula

### PR DESCRIPTION
**Pull request by chad-ermacora**
I found this formula to be more accurate when the altitude is below 11km.

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Thank you for taking the time to PR this. 

This is interesting- do you have any sources for the reasoning behind the formula? It would be really handy to document this for future reference.

You should also update the tests in `test_compensation.py` so that their expectations match the output of the new forumla. You should be able to see the test output here: https://travis-ci.com/github/pimoroni/bmp280-python/jobs/343169368

These tests are a crude guard against regressions, but in this case since you're explicitly changing the formula they can be safely amended.

**Comment by chad-ermacora** [comment]
This is where I found the [Altitude Formula](https://keisan.casio.com/exec/system/1224585971)

I'll add it to the other areas shortly.  Also, any of your other sensors that support Temperature and Pressure can find altitude with this.

**Comment by Gadgetoid** [comment]
Thank you for the tweaks and information. And, of course, for the revised formula!- I'm going to merge this for others to play with, and then figure out how this change is best communicated in a release.

**Comment by chad-ermacora** [comment]
You're Welcome!  

I have only been able to test it at my location and one other.  And although it was more accurate, it's still not super accurate, but at least it doesn't go into negatives for someone I was working with at just above sea level.  Also, something to keep in mind, since it uses temperature to help determine altitude, using it indoors will throw off the readings.  

Out of curiosity, did you try the adjusted formula at your location outdoors?  Was it more accurate there?

**Comment by Gadgetoid** [comment]
I - admittedly - have not yet had the opportunity to test it. I didn't want that to prevent me merging.  Onwards and upwards!

Right now I'm working from home and somewhat lacking in equipment and opportunity to do this justice.

I wonder if it's worth allowing the temperature to be supplied to `get_altitude` as an optional parameter, with the default being the "local" temperature of the sensor.

**Comment by chad-ermacora** [comment]
That's a good idea.  I'll make another pull request with that change, then we can discuss it there.

**Pull request merged**
